export const clinicalBriefSchema = {
  name: "clinical_brief",
  strict: true,
  schema: {
    type: "object",
    properties: {
      patient_name: { type: "string" },
      patient_age: { type: ["number", "null"] },
      chief_complaint: { type: "string" },
      complaint_category: { type: "string" },
      symptoms: {
        type: "array",
        items: { type: "string" },
      },
      symptom_duration: { type: "string" },
      severity: {
        type: "string",
        enum: ["mild", "moderate", "severe"],
      },
      urgency_level: {
        type: "string",
        enum: ["routine", "urgent", "emergency"],
      },
      associated_symptoms: {
        type: "object",
        properties: {
          pain: { type: "boolean" },
          redness: { type: "boolean" },
          watering_discharge: { type: "boolean" },
          flashes_floaters: { type: "boolean" },
        },
        required: ["pain", "redness", "watering_discharge", "flashes_floaters"],
        additionalProperties: false,
      },
      onset_type: {
        type: "string",
        enum: ["sudden", "gradual", "unknown"],
      },
      onset_context: {
        type: "string",
        enum: ["spontaneous", "trauma", "post_event", "unknown"],
      },
      onset_details: { type: "string" },
      prior_ophthalmic_care: { type: "string" },
      past_ocular_treatment: { type: "string" },
      systemic_illness: {
        type: "array",
        items: { type: "string" },
      },
      red_flags: {
        type: "array",
        items: { type: "string" },
      },
      highlight_points: {
        type: "array",
        items: { type: "string" },
      },
      differential_diagnosis: {
        type: "array",
        items: { type: "string" },
      },
      medical_history: {
        type: "array",
        items: { type: "string" },
      },
      current_medications: {
        type: "array",
        items: { type: "string" },
      },
      allergies: {
        type: "array",
        items: { type: "string" },
      },
      recommended_action: { type: "string" },
      clinical_summary: { type: "string" },
      insufficient_information: { type: "boolean" },
    },
    required: [
      "patient_name",
      "patient_age",
      "chief_complaint",
      "complaint_category",
      "symptoms",
      "symptom_duration",
      "severity",
      "urgency_level",
      "associated_symptoms",
      "onset_type",
      "onset_context",
      "onset_details",
      "prior_ophthalmic_care",
      "past_ocular_treatment",
      "systemic_illness",
      "red_flags",
      "highlight_points",
      "differential_diagnosis",
      "medical_history",
      "current_medications",
      "allergies",
      "recommended_action",
      "clinical_summary",
      "insufficient_information",
    ],
    additionalProperties: false,
  },
};
